http:
    server.socket_host: 0.0.0.0
    server.socket_port: 1111
    engine.autoreload.on: true

mongo:
    host: 127.0.0.1
    database: riverrun

convert: ebook-convert

library: "./library/{authors} - {title}.{ext}"
